TwoSSome/poompoom-web

- package-lock.json
- package.json
- yarn.lock
- #9 feat: styled-component install
<br/>
-
> feat: styled-component install

- src/App.js
- src/components/Footer/Footer.styles.js
- src/components/Header/Header.styles.js
- src/shared/Theme.js
-header, footer styled-componenet에  theme 적용
#13 
<br/>
-
> feat: themeProvider 적용

- public/reset.css
- src/App.js
- src/components/PointModal/PointModal.js
- src/components/QuickGift/QuickGift.js
- src/components/RankingProfileCard/RankingProfileCard.js
- src/components/ReviewPost/ReviewPost.js
- src/components/ReviewPostBackground/ReviewPostBackground.js
- src/components/ReviewPostBody/ReviewPostBody.js
- src/components/ReviewPostHeader/ReviewPostHeader.js
- src/components/ReviewPostShortcut/ReviewPostShortcut.js
- src/pages/Review.js
- src/pages/ReviewPage.js
- yarn.lock
- #14 
<br/>
- container, presentation 패턴은 컴포넌트 구현 완료 후에 적용시키도록 하겠습니다!
> 리뷰글 페이지 컴포넌트 분리

- src/App.js
- src/components/Community/Comment/CommentList/CommentList.js
- src/components/Community/Comment/CommentWrite/CommentWrite.js
- src/components/Community/CommunityDetail/CommunityDetail.js
- src/components/Community/CommunityList/CommunityList.js
- src/components/Community/CommunityWrite/CommunityWrite.js
- src/pages/Community/Detail/CommunityDetailPage.js
- src/pages/Community/List/CommunityPage.js
- src/pages/Community/new/CommunityWritePage.js
- yarn.lock
- #16 
<br/>
- 저도 일단 conatainer/presenter 패턴 적용 안하고 올리겠습니다!
> feat:community 기본 기능 구현

- src/App.js
- src/components/Footer/Footer.styles.js
- src/components/Header/Header.container.js
- src/components/Header/Header.presenter.js
- src/components/Header/Header.styles.js
- src/components/PointModal/PointModal.js
- src/components/PostSearch/PostSearch.js
- src/components/QuickGift/QuickGift.js
- src/components/ReviewPost/ReviewPost.js
- src/components/ReviewPostBackground/ReviewPostBackground.js
- src/components/ReviewPostBox/ReviewPostBox.js
- src/components/ReviewPostHeader/ReviewPostHeader.js
- src/hooks/useDebounce.js
- src/hooks/useModal.js
- src/pages/HomePage.js
- src/pages/ProfilePage.js
- src/pages/ReviewPage.js
- yarn.lock
- #18 
- 리뷰글 페이지에서 ReviewPostBox로 분리
- 그림 클릭 시 오류 해결
- 프로필 페이지 레이아웃 구성
- 홈 페이지 레이아웃 구성
<br/>
- useModal, useDebounce 커스텀 훅 생성했습니다. useDebounce는 아직 미완성입니다.
> 리뷰글 페이지 수정 및 프로필 페이지, 홈 페이지 컴포넌트 분리

- src/App.js
- src/components/PointModal/PointModal.js
- src/components/PostDetail/PostDetail.js
- src/pages/Profile/components/ProfileBody/ProfileBody.js
- src/pages/Review/ReviewPage.js
- src/pages/Review/components/ReviewPost/ReviewPost.js
모달창 css변경
라우팅 url 주소 변경 
- #27 
<br/>
-
> fix: 모달창 css 변경

- src/App.js
- src/components/Header/Header.styles.js
- src/components/PostDetail/PostDetail.container.js
- src/components/PostDetail/PostDetail.persenter.js
- src/pages/Review/components/Card/ReviewPostPreview/ReviewPostPreview.presenter.js
- src/pages/Review/components/Ranking/Card/Card.conatiner.js
- src/pages/Review/components/Ranking/Card/Card.presenter.js
- src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.container.js
- src/pages/Review/components/Ranking/RankingProfileCard/RankingProfileCard.presenter.js
- src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.container.js
- src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.presenter.js
- src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.container.js
- src/pages/Review/components/Section/SearchSection/SearchGallery/SearchGallery.presenter.js
- src/pages/Review/components/Section/SubSection/SubGallery/SubGallery.presenter.js
- #41 
<br/>
- useLocation활용해서 하는거 /review만 남겨뒀는데, 저 정보도 사실 정적 더미 데이터인거죠?
> 리뷰 자세히보기 라우팅 연결

- package-lock.json
- package.json
- src/App.js
- src/pages/Login/LoginPage.js
- src/pages/Login/SignUpPage.js
- src/pages/Login/components/SignUp/SignUp.js
- src/pages/Login/components/SignUp/SignUp.style.js
- src/pages/Login/components/SignUp/SignUp.validation.js
- yarn.lock
-  react-hook-form & yup으로 회원가입 폼 작성, 간단한 유효성검사
<br/>
-
> feat: react-hook-form & yup으로 회원가입 폼 작성

- src/pages/SignUp/component/SignUpTag/SignUpTag.js
- src/pages/SignUp/component/SignUpTag/component/Gender.js
- src/pages/SignUp/component/SignUpTag/component/Interest.js
- src/pages/SignUp/component/SignUpTag/component/Job.js
- #52 
<br/>
-분기를 여러 개 생성하여 풀리퀘를 따로 올립니다
> 사용자 태그 입력창 UI

- src/pages/QuickGift/QuickGift.js
- src/pages/QuickGift/QuickGiftPage.js
- src/pages/QuickGift/component/Age.js
- src/pages/QuickGift/component/Image.js
- src/pages/QuickGift/component/Interest.js
- src/pages/QuickGift/component/Job.js
- src/pages/QuickGift/component/Purpose.js
- src/pages/SignUp/SignUpTagPage.js
- src/pages/SignUp/component/SignUp/SignUp.js
- src/pages/SignUp/component/SignUp/SignUp.validation.js
- src/pages/SignUp/component/SignUpTag/SignUpTag.js
- src/pages/SignUp/component/SignUpTag/component/Gender.js
- src/pages/SignUp/component/SignUpTag/component/Interest.js
- src/pages/SignUp/component/SignUpTag/component/Job.js
> 회원가입 기능 개발

- src/pages/QuickGift/QuickGift.js
- src/pages/QuickGift/QuickGiftPage.js
- src/pages/QuickGift/component/Age.js
- src/pages/QuickGift/component/Image.js
- src/pages/QuickGift/component/Interest.js
- src/pages/QuickGift/component/Job.js
- src/pages/QuickGift/component/Purpose.js
- src/pages/SignUp/component/SignUpTag/SignUpTag.js
- src/pages/SignUp/component/SignUpTag/component/Gender.js
- src/pages/SignUp/component/SignUpTag/component/Interest.js
- src/pages/SignUp/component/SignUpTag/component/Job.js
- #52 
<br/>
- 분기를 따로 설정하여 풀리퀘를 여러 번 올립니다 ㅠ 제일 첫번쨰 풀리퀘에 타 풀리퀘의 커밋 내용이 포함되어있습니다
> 연인 간 빠른 선물하기 UI

- .env
- package.json
- public/index.html
- src/index.js
- yarn.lock
- GitHub Pages URL redirect
<br/>
-
> GitHub Pages URL redirect

- public/index.html
- index.html PUBLIC URL 삭제 및 homepage 라우팅 수정
<br/>
-
> Bug: index.html PUBLIC URL 삭제 및 homepage 라우팅 수정

- .env
- public/index.html
> fix: PUBLIC URL 추가

- src/index.js
- src/pages/Login/components/Login.js
- src/pages/Profile/components/ProfileBody/component/My.js
- src/pages/Review/components/Section/LatestSection/LatestGallery/LatestGallery.container.js
> feat: 프로필 api 

- src/App.js
- src/apis/refresh.js
- src/components/AuthorComponent.js
- src/index.js
- src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.presenter.js
- src/pages/Review/components/Card/ReviewPostBackground/ReviewPostBackground.presenter.js
- src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.presenter.js
- src/pages/Review/components/Card/ReviewPostHashtags/ReviewPostHashtags.presenter.js
- src/pages/Review/components/Card/ReviewPostPreview/ReviewPostPreview.presenter.js
- src/pages/SignUp/SignUpPage.js
- src/pages/SignUp/SignUpTagPage.js
- src/pages/SignUp/component/SignUp/SignUp.js
- src/pages/SignUp/component/SignUpTag/SignUpTag.js
> 로그인 API 호출URL 수정

- src/App.js
- src/components/AuthorComponent.js
- src/pages/QueryResult/QueryResultPage.js
- src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.container.js
- src/pages/Review/components/Card/ReviewPostAuthor/ReviewPostAuthor.presenter.js
- src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.container.js
- src/pages/Review/components/Card/ReviewPostCard/ReviewPostCard.presenter.js
> Login 파일 경로 수정

- src/components/PostDetail/PostDetail.container.js
- src/components/PostDetail/PostDetail.presenter.js
> fix: 리뷰창 클릭시 연결

- src/components/PostComment/PostCommentList/PostCommentList.container.js
- src/components/PostComment/PostCommentList/PostCommentList.presenter.js
- src/components/PostComment/PostCommentList/PostCommentList.styles.js
- src/components/PostComment/PostCommentWrite/PostCommentWrite.container.js
- src/components/PostDetail/PostDetail.presenter.js
- src/components/PostDetail/PostDetail.styles.js
- src/pages/Review/components/QuickGift/SetQuickGift.js
- http://localhost:3000/review/50 에서 확인해보세용
<br/>
-
> feat: 댓글 작성, 보기 기능

- src/apis/axios.js
- src/components/PostFilter/PostFilter.presenter.js
- axios 인스턴스 수정
<br/>
- 32번째 github pages 배포 환경 유지 가능하도록 백업 폴더 생성.
> axios 헤더에 Content-Type 명시

- package.json
- public/index.html
- Hompage 속성 netlify URL 설정
<br/>
-
> Hompage 속성 netlify URL 설정

- public/index.html
- Mixed Content meta 태그 제거
<br/>
-
> Mixed Content meta 태그 제거

- .env
- src/App.js
- src/ProtectedRoute.js
- src/components/Footer/Footer.styles.js
- src/components/Header/Header.styles.js
- src/components/PostFilter/PostFilter.presenter.js
- src/components/PostFilter/PostFilter.styles.js
- src/components/PostFilter/PriceSlider.js
- src/pages/Review/ReviewPage.js
- src/pages/ReviewDetail/PostDetail/PostDetail.container.js
- src/pages/ReviewDetail/PostDetail/PostDetail.presenter.js
- src/pages/ReviewWrite/ReviewWritePage.js
- #105 
- #106 
<br/>
- 디스플레이 가로가 1460px 이하로 줄어들 때, 레이아웃이 깨지는 현상 발생하여 수정함
- 추후 레이아웃 CSS만 모듈화하여 정리할 것.
> 필터 정렬 기능 추가 및 레이아웃 수정

- src/pages/Calendar/CalendarPage.js
- src/pages/Calendar/components/CalendarView/CalendarView.js
- src/pages/Calendar/components/Sidebar/Sidebar.js
- src/pages/Join/Signup/SignupPage.js
- src/pages/index.js
- src/routes/AppRoutes.js
- 사이드바와 메인 뷰로 나눠놨습니다.  
<br/>
-
> feat: 캘린더 프레임 제작 및 회원가입 중복체크 로직  추가

- src/pages/Calendar/CalendarPage.js
- src/pages/Calendar/components/CalendarView/CalendarView.js
- src/pages/Calendar/components/CalendarView/EventDetailModal.js
- src/pages/Calendar/components/CalendarView/EventModal.js
- src/pages/Calendar/components/CalendarView/PostDetailModal.js
- src/pages/Calendar/components/CalendarView/PostModal.js
- src/pages/index.js
- src/routes/AppRoutes.js
임시 디자인 프로토타입 구현
- CalendarView 디자인 프로토타입 구현
<br/>
- /calendar로 엔드 포인트 변경되었습니다.
- 일부 calendar 파일명 수정했습니다.
> feat: calendar view 프로토타입 구현

- src/pages/Calendar/components/CalendarView/PostModal.js
- src/pages/Calendar/components/Sidebar/Section/PoomPoom.js
-  품품로그 정렬 기준을 선택된 날자로 변경 
<br/>
-
> feat: 게시글 날짜 선택 창 추가

- src/pages/Calendar/components/CalendarView/CalendarView.js
- src/pages/Calendar/components/CalendarView/EventCreateModal.js
- src/pages/Calendar/components/CalendarView/EventDetailModal.js
- src/pages/Calendar/components/CalendarView/PostCreateModal.js
- src/pages/Calendar/components/CalendarView/PostDetailModal.js
- 메모 조회, 작성 구분
- 일정 기간 표시 버그 수정
- 작성 모달 컴포넌트명 수정
- 게시글 작성 본문 HTML 데이터구조로 수정
<br/>
-
> feat: 카테고리에 따른 일정 입력 데이터 변경
